services:
  - type: web
    name: babycare-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
    healthCheckPath: /health
    healthCheckTimeout: 10
    autoDeploy: true
    # Дополнительные настройки для предотвращения "сна"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: KEEP_ALIVE_INTERVAL
        value: "5"
